apiVersion: v1
kind: Service
metadata:
  name: hello-nodeport-pod
  labels:
    component: hello-nodeport-pod
spec:
  type: NodePort
  selector:
    component: hello-pod
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
